version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: manajemen-ujian-laravel-app
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    
    networks:
      - manajemen-ujian-laravel-net

  webserver:
    image: nginx:1.25.3
    container_name: manajemen-ujian-laravel-webserver

    ports:
      - 8001:80
    
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - manajemen-ujian-laravel-net
  
networks:
  manajemen-ujian-laravel-net:
    driver: bridge