version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: semi-ujian-laravel-app
    working_dir: /var/www

    volumes:
      - ./:/var/www
    
    networks:
      - semi-ujian-laravel-net

  webserver:
    image: nginx:alpine
    container_name: semi-ujian-laravel-webserver

    ports:
      - 8001:80
    
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - semi-ujian-laravel-net
  
  db:
    image: mariadb:10.7.8
    container_name: semi-ujian-laravel-db

    ports:
      - 3001:3306
    
    environment:
      MARIADB_ROOT_PASSWORD: 'toor'
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    
    volumes:
      - semi-ujian-laravel-data:/var/lib/mysql
    
    networks:
      - semi-ujian-laravel-net
    

volumes:
  semi-ujian-laravel-data:
    driver: local


networks:
  semi-ujian-laravel-net:
    driver: bridge