version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: manajemen-ujian-laravel-app
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    
    networks:
      - manajemen-ujian-laravel-net

  webserver:
    image: nginx:1.25.3
    container_name: manajemen-ujian-laravel-webserver

    ports:
      - 8001:80
    
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - manajemen-ujian-laravel-net
  
#   db:
#     image: mariadb:10.7.8
#     container_name: manajemen-ujian-laravel-db

#     ports:
#       - 3001:3306
    
#     environment:
#       MARIADB_ROOT_PASSWORD: 'toor'
#       MARIADB_DATABASE: ${DB_DATABASE}
#       MARIADB_USER: ${DB_USERNAME}
#       MARIADB_PASSWORD: ${DB_PASSWORD}
    
#     volumes:
#       - manajemen-ujian-laravel-data:/var/lib/mysql
    
#     networks:
#       - manajemen-ujian-laravel-net
    

# volumes:
#   manajemen-ujian-laravel-data:
#     driver: local


networks:
  manajemen-ujian-laravel-net:
    driver: bridge